# Generated by Django 4.2.2 on 2023-07-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='description',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='activ',
            field=models.BooleanField(default=True),
        ),
    ]
